Add test - SecQuery::Entity.find should return nil when result not found
............F.................................

Failures:

  1) SecQuery::Entity Entity cannot be found returns nil
     Failure/Error: if content['company_info'].present?

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/sec_query/entity.rb:45:in `parse'
     # ./lib/sec_query/entity.rb:40:in `find'
     # ./spec/sec_query/entity_spec.rb:43:in `block (3 levels) in <top (required)>'

Finished in 2.29 seconds (files took 1.54 seconds to load)
46 examples, 1 failure

Failed examples:

rspec ./spec/sec_query/entity_spec.rb:42 # SecQuery::Entity Entity cannot be found returns nil